apiVersion: v1
kind: Service
metadata:
  labels:
    run: facturaspersistidorms
  name: facturaspersistidorms
  namespace: default  
spec:
  selector:
   run: facturaspersistidorms
  ports:
  - port: 8080
    targetPort: 8080    
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: facturaspersistidorms
  name: facturaspersistidorms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: facturaspersistidorms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: facturaspersistidorms
    spec:           
      containers:
      - image: amm1992/facturaspersistidorms:v1
        imagePullPolicy: Always
        name: facturaspersistidorms
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /persistidorFacturas/readinessProbe/isOk
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: SERVICIO_MONGODB_USERNAME
          valueFrom:
             secretKeyRef:
                name: servicio-mongodb
                key: username
        - name: SERVICIO_MONGODB_PASSWORD
          valueFrom:
             secretKeyRef:
                name: servicio-mongodb
                key: password
        - name: SERVICIO_MONGODB_AUTH
          valueFrom:
             secretKeyRef:
                name: servicio-mongodb
                key: database
        - name: SERVICIO_MONGODB_DB
          valueFrom:
             configMapKeyRef:
                name: servicio-mongodb-config
                key: database
        - name: SERVICIO_MONGODB_HOST
          valueFrom:
             configMapKeyRef:
                name: servicio-mongodb-config
                key: hostname
        - name: SERVICIO_MONGODB_PORT
          valueFrom:
             configMapKeyRef:
                name: servicio-mongodb-config
                key: port
             
        
