apiVersion: v1
kind: Service
metadata:
  labels:
    run: portalfacturasms
  name: portalfacturasms
  namespace: default  
spec:
  selector:
   run: portalfacturasms
  ports:
  - port: 8080
    targetPort: 8080
    name: portalfacturasmsport
    protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: portalfacturasms
  name: portalfacturasms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: portalfacturasms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: portalfacturasms
    spec:           
      containers:
      - image: amm1992/portalfacturasms:v1
        imagePullPolicy: Always
        name: portalfacturasms
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /portalFacturas/readinessProbe/isOk
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5        
        env:
        - name: SERVICIO_REDIS_HOST
          valueFrom:
             configMapKeyRef:
                name: servicio-redis
                key: host
        - name: SERVICIO_REDIS_PORT
          valueFrom:
             configMapKeyRef:
                name: servicio-redis
                key: port        
        
